# Generated by Django 2.1 on 2019-04-23 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=251)),
                ('last_name', models.CharField(max_length=251)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please select a valid phone number.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[(0, 'REGULAR'), (1, 'ADMIN')], max_length=64)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_member',
            },
        ),
    ]
